/* ============================================================
   Banque de questions du simulateur d'entretien technique
   Stack adaptée : C# / .NET, ASP.NET Core, EF Core, Angular,
   JavaScript/TypeScript, CSS, Git, SQL, Agile.
   (Données générées et vérifiées via recherche, format JSON valide en JS)
   ============================================================ */

const CSHARP_MCQ = [
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Quel sera le résultat affiché par ce programme ?","code":"struct Point { public int X; }\n\nclass Program\n{\n    static void Main()\n    {\n        Point a = new Point { X = 10 };\n        Point b = a;\n        b.X = 20;\n        Console.WriteLine(a.X);\n    }\n}","options":["10","20","0","Erreur de compilation"],"correctIndex":0,"explanation":"Un struct est un type valeur : l'affectation 'b = a' copie l'instance entière, donc modifier b.X n'affecte pas a.X qui reste à 10.","difficulty":"easy"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Que se passe-t-il lorsqu'on exécute ce code ?","code":"int? a = null;\nint b = a ?? 5;\nint c = a.GetValueOrDefault();\nConsole.WriteLine($\"{b} {c}\");","options":["5 0","0 5","5 5","NullReferenceException levée"],"correctIndex":0,"explanation":"L'opérateur ?? renvoie 5 car a est null ; GetValueOrDefault() renvoie la valeur par défaut de int (0) sans lever d'exception.","difficulty":"easy"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Quelle affirmation est correcte concernant les chaînes de caractères en C# ?","code":"string s = \"hello\";\ns.ToUpper();\nConsole.WriteLine(s);","options":["Affiche \"HELLO\" car ToUpper modifie la chaîne","Affiche \"hello\" car string est immuable","Erreur de compilation","Affiche une chaîne vide"],"correctIndex":1,"explanation":"string est immuable : ToUpper() retourne une nouvelle chaîne sans modifier l'originale, et ici le résultat n'est pas réassigné, donc s vaut toujours \"hello\".","difficulty":"easy"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Parmi ces opérations, laquelle provoque un boxing ?","code":null,"options":["int i = 42; int j = i;","int i = 42; object o = i;","string s = \"hi\"; object o = s;","int i = 42; long l = i;"],"correctIndex":1,"explanation":"Le boxing convertit un type valeur (int) en type référence (object) en l'encapsulant sur le tas managé ; assigner un string (déjà type référence) à un object n'est pas du boxing.","difficulty":"medium"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Quelle est la différence clé entre une interface et une classe abstraite en C# ?","code":null,"options":["Une classe peut hériter de plusieurs classes abstraites mais d'une seule interface","Une classe peut implémenter plusieurs interfaces mais n'hériter que d'une seule classe abstraite","Les interfaces peuvent avoir des champs d'instance, pas les classes abstraites","Une classe abstraite ne peut contenir aucune implémentation de méthode"],"correctIndex":1,"explanation":"C# ne supporte pas l'héritage multiple de classes : une classe n'hérite que d'une seule classe (abstraite ou non), mais peut implémenter plusieurs interfaces.","difficulty":"medium"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Quel sera le résultat de l'exécution de ce code LINQ ?","code":"var nums = new List<int> { 1, 2, 3, 4, 5 };\nvar result = nums.Where(n => n > 2).Select(n => n * 2);\nConsole.WriteLine(string.Join(\",\", result));","options":["2,4,6,8,10","6,8,10","3,4,5","2,4,6"],"correctIndex":1,"explanation":"Where filtre les éléments strictement supérieurs à 2 (3, 4, 5), puis Select les multiplie par 2, donnant 6, 8, 10.","difficulty":"easy"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Que renvoie cette méthode async ?","code":"async Task<int> GetValueAsync()\n{\n    await Task.Delay(100);\n    return 42;\n}","options":["La valeur int 42 directement","Un Task<int> qui produira 42 une fois terminé","Rien, le type de retour devrait être void","Un int? valant null tant que la tâche n'est pas finie"],"correctIndex":1,"explanation":"Une méthode async qui retourne 42 avec un type déclaré Task<int> renvoie un Task<int> ; la valeur 42 est obtenue en awaitant ce Task.","difficulty":"medium"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"À quoi sert principalement le bloc 'using' avec un objet dans ce code ?","code":"using (var file = new StreamReader(\"data.txt\"))\n{\n    var content = file.ReadToEnd();\n}","options":["À importer un namespace localement","À appeler automatiquement Dispose() de l'objet à la sortie du bloc","À rendre l'objet immuable dans le bloc","À exécuter le code de façon asynchrone"],"correctIndex":1,"explanation":"L'instruction using appelle automatiquement Dispose() sur l'objet (qui implémente IDisposable) à la fin du bloc, même en cas d'exception, libérant les ressources.","difficulty":"easy"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Quel sera l'affichage de ce code utilisant out ?","code":"void Add(int x, out int result)\n{\n    result = x + 10;\n}\n\nint value;\nAdd(5, out value);\nConsole.WriteLine(value);","options":["5","0","15","Erreur : value n'est pas initialisée"],"correctIndex":2,"explanation":"Un paramètre out doit être assigné dans la méthode et la valeur est renvoyée à l'appelant ; result = 5 + 10 = 15, donc value vaut 15.","difficulty":"medium"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Que va afficher ce code utilisant un record ?","code":"record Person(string Name, int Age);\n\nvar p1 = new Person(\"Alice\", 30);\nvar p2 = new Person(\"Alice\", 30);\nConsole.WriteLine(p1 == p2);","options":["True","False","Erreur de compilation","Dépend des références mémoire"],"correctIndex":0,"explanation":"Les records utilisent l'égalité par valeur : p1 == p2 compare les valeurs des propriétés (Name et Age identiques), donc le résultat est True.","difficulty":"medium"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Quel sera le résultat de ce pattern matching avec switch expression ?","code":"object obj = 7;\nstring res = obj switch\n{\n    int n when n > 5 => \"grand\",\n    int n => \"petit\",\n    _ => \"autre\"\n};\nConsole.WriteLine(res);","options":["\"grand\"","\"petit\"","\"autre\"","Erreur de compilation"],"correctIndex":0,"explanation":"obj contient un int valant 7 ; le premier motif 'int n when n > 5' est satisfait (7 > 5), donc le résultat est \"grand\".","difficulty":"medium"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Que se passe-t-il à l'exécution de ce code avec un Dictionary ?","code":"var dict = new Dictionary<string, int>();\ndict[\"a\"] = 1;\nint x = dict[\"b\"];\nConsole.WriteLine(x);","options":["Affiche 0","Affiche null","Lève une KeyNotFoundException","Ajoute \"b\" avec la valeur 0"],"correctIndex":2,"explanation":"Accéder à une clé absente via l'indexeur dict[\"b\"] lève une KeyNotFoundException ; il faut utiliser TryGetValue ou ContainsKey pour éviter cela.","difficulty":"medium"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Quelle est la principale différence entre 'var' et 'dynamic' en C# ?","code":null,"options":["var et dynamic sont des synonymes, sans différence","var est résolu à la compilation (typage statique inféré), dynamic reporte la résolution de type à l'exécution","dynamic est résolu à la compilation, var à l'exécution","var ne peut s'utiliser que pour les types valeur"],"correctIndex":1,"explanation":"var infère un type statique à la compilation (le type est fixé) ; dynamic contourne la vérification de type au compile-time et résout les membres à l'exécution.","difficulty":"medium"},
  {"category":"C#","subcategory":"Language knowledge","type":"mcq","question":"Quel sera le résultat de ce code utilisant un délégué et une expression lambda ?","code":"Func<int, int, int> op = (a, b) => a * b;\nFunc<int, int, int> op2 = (a, b) => a + b;\nConsole.WriteLine(op(3, 4) + op2(3, 4));","options":["12","7","19","Erreur de compilation"],"correctIndex":2,"explanation":"op(3, 4) calcule 3 * 4 = 12 et op2(3, 4) calcule 3 + 4 = 7 ; la somme finale affichée est 12 + 7 = 19.","difficulty":"medium"}
];

const CSHARP_CODE = [
  {"category":"C#","subcategory":"Problem solving","type":"code","language":"csharp","prompt":"Implémentez la méthode `IsPalindrome` qui renvoie `true` si la chaîne fournie est un palindrome (se lit pareil dans les deux sens), et `false` sinon. La comparaison doit être insensible à la casse et ignorer les espaces.","starterCode":"using System;\n\npublic class Palindrome\n{\n    public static bool IsPalindrome(string input)\n    {\n        // TODO: implémenter\n        throw new NotImplementedException();\n    }\n}","solution":"using System;\nusing System.Linq;\n\npublic class Palindrome\n{\n    public static bool IsPalindrome(string input)\n    {\n        if (input == null)\n            return false;\n\n        var cleaned = new string(\n            input.Where(c => !char.IsWhiteSpace(c))\n                 .Select(char.ToLowerInvariant)\n                 .ToArray());\n\n        int left = 0;\n        int right = cleaned.Length - 1;\n        while (left < right)\n        {\n            if (cleaned[left] != cleaned[right])\n                return false;\n            left++;\n            right--;\n        }\n        return true;\n    }\n}","tests":[{"input":"\"kayak\"","expected":"true"},{"input":"\"bonjour\"","expected":"false"},{"input":"\"A man a plan\"","expected":"false"},{"input":"\"radar\"","expected":"true"}],"explanation":"On nettoie la chaîne (sans espaces, en minuscules), puis on utilise deux pointeurs qui se rapprochent du centre : si deux caractères en miroir diffèrent, ce n'est pas un palindrome. O(n) en temps.","difficulty":"easy"},
  {"category":"C#","subcategory":"Problem solving","type":"code","language":"csharp","prompt":"Implémentez la méthode `Convert` qui prend un entier `n` et renvoie une liste de chaînes de 1 à `n` selon les règles de FizzBuzz : multiples de 3 -> \"Fizz\", multiples de 5 -> \"Buzz\", multiples de 3 et 5 -> \"FizzBuzz\", sinon le nombre en texte.","starterCode":"using System;\nusing System.Collections.Generic;\n\npublic class FizzBuzz\n{\n    public static List<string> Convert(int n)\n    {\n        // TODO: implémenter\n        throw new NotImplementedException();\n    }\n}","solution":"using System;\nusing System.Collections.Generic;\n\npublic class FizzBuzz\n{\n    public static List<string> Convert(int n)\n    {\n        var result = new List<string>();\n        for (int i = 1; i <= n; i++)\n        {\n            if (i % 15 == 0) result.Add(\"FizzBuzz\");\n            else if (i % 3 == 0) result.Add(\"Fizz\");\n            else if (i % 5 == 0) result.Add(\"Buzz\");\n            else result.Add(i.ToString());\n        }\n        return result;\n    }\n}","tests":[{"input":"Convert(3)","expected":"[\"1\", \"2\", \"Fizz\"]"},{"input":"Convert(5)","expected":"[\"1\", \"2\", \"Fizz\", \"4\", \"Buzz\"]"},{"input":"Convert(15)[14]","expected":"\"FizzBuzz\""},{"input":"Convert(0)","expected":"[] (liste vide)"}],"explanation":"On teste d'abord la divisibilité par 15 (3 et 5) car c'est le cas le plus restrictif ; le faire en premier évite de combiner les conditions. L'ordre des conditions est crucial.","difficulty":"easy"},
  {"category":"C#","subcategory":"Problem solving","type":"code","language":"csharp","prompt":"Implémentez la méthode `AreAnagrams` qui renvoie `true` si les deux chaînes sont des anagrammes (mêmes lettres, mêmes quantités, ordre différent), insensible à la casse et aux espaces.","starterCode":"using System;\n\npublic class Anagram\n{\n    public static bool AreAnagrams(string a, string b)\n    {\n        // TODO: implémenter\n        throw new NotImplementedException();\n    }\n}","solution":"using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\npublic class Anagram\n{\n    public static bool AreAnagrams(string a, string b)\n    {\n        if (a == null || b == null) return false;\n        var counts = new Dictionary<char, int>();\n        foreach (var c in Normalize(a))\n            counts[c] = counts.GetValueOrDefault(c, 0) + 1;\n        foreach (var c in Normalize(b))\n        {\n            if (!counts.ContainsKey(c)) return false;\n            counts[c]--;\n            if (counts[c] == 0) counts.Remove(c);\n        }\n        return counts.Count == 0;\n    }\n\n    private static IEnumerable<char> Normalize(string s) =>\n        s.Where(c => !char.IsWhiteSpace(c)).Select(char.ToLowerInvariant);\n}","tests":[{"input":"AreAnagrams(\"chien\", \"niche\")","expected":"true"},{"input":"AreAnagrams(\"Marie\", \"aimer\")","expected":"true"},{"input":"AreAnagrams(\"abc\", \"abd\")","expected":"false"},{"input":"AreAnagrams(\"abc\", \"ab\")","expected":"false"}],"explanation":"On compte les caractères de la 1re chaîne dans un dictionnaire, puis on décrémente pour chaque caractère de la 2e. Un caractère manquant ou un compteur non nul à la fin = pas anagrammes. O(n), plus efficace que trier.","difficulty":"easy"},
  {"category":"C#","subcategory":"Problem solving","type":"code","language":"csharp","prompt":"Implémentez `MostFrequent` qui renvoie le caractère le plus fréquent d'une chaîne. En cas d'égalité, renvoyez celui qui apparaît en premier. Si la chaîne est vide, renvoyez '\\0'.","starterCode":"using System;\n\npublic class CharFrequency\n{\n    public static char MostFrequent(string input)\n    {\n        // TODO: implémenter\n        throw new NotImplementedException();\n    }\n}","solution":"using System;\nusing System.Collections.Generic;\n\npublic class CharFrequency\n{\n    public static char MostFrequent(string input)\n    {\n        if (string.IsNullOrEmpty(input)) return '\\0';\n        var counts = new Dictionary<char, int>();\n        char best = input[0];\n        int bestCount = 0;\n        foreach (var c in input)\n        {\n            counts[c] = counts.GetValueOrDefault(c, 0) + 1;\n            if (counts[c] > bestCount)\n            {\n                bestCount = counts[c];\n                best = c;\n            }\n        }\n        return best;\n    }\n}","tests":[{"input":"MostFrequent(\"aabbbc\")","expected":"'b'"},{"input":"MostFrequent(\"abcabc\")","expected":"'a'"},{"input":"MostFrequent(\"x\")","expected":"'x'"},{"input":"MostFrequent(\"\")","expected":"'\\0'"}],"explanation":"On parcourt une fois en maintenant un dictionnaire de compteurs. Le `>` strict (et non `>=`) garantit qu'en cas d'égalité, c'est le caractère rencontré en premier qui gagne.","difficulty":"medium"},
  {"category":"C#","subcategory":"Problem solving","type":"code","language":"csharp","prompt":"À partir d'une liste de commandes `Order` (CustomerId, Amount, IsPaid), implémentez `TopCustomers` qui renvoie avec LINQ les identifiants des 3 clients ayant le plus dépensé (commandes payées seulement), triés par total décroissant.","starterCode":"using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\npublic class Order\n{\n    public int CustomerId { get; set; }\n    public decimal Amount { get; set; }\n    public bool IsPaid { get; set; }\n}\n\npublic class Analytics\n{\n    public static List<int> TopCustomers(List<Order> orders)\n    {\n        // TODO: implémenter avec LINQ\n        throw new NotImplementedException();\n    }\n}","solution":"public static List<int> TopCustomers(List<Order> orders)\n{\n    if (orders == null) return new List<int>();\n    return orders\n        .Where(o => o.IsPaid)\n        .GroupBy(o => o.CustomerId)\n        .Select(g => new { CustomerId = g.Key, Total = g.Sum(o => o.Amount) })\n        .OrderByDescending(x => x.Total)\n        .Take(3)\n        .Select(x => x.CustomerId)\n        .ToList();\n}","tests":[{"input":"1:200 payé, 2:500 payé, 3:100 payé","expected":"[2, 1, 3]"},{"input":"client 1 (100+150), client 2 (200)","expected":"[1, 2]"},{"input":"toutes IsPaid = false","expected":"[] (liste vide)"}],"explanation":"Pipeline LINQ : Where (payées) -> GroupBy (client) -> Sum (total) -> OrderByDescending -> Take(3) -> Select identifiants. Take est sûr même avec moins de 3 clients.","difficulty":"medium"},
  {"category":"C#","subcategory":"Reliability","type":"code","language":"csharp","prompt":"La méthode `Average` calcule la moyenne d'un tableau d'entiers mais plante dans plusieurs cas. Corrigez-la : renvoyer 0 si le tableau est null ou vide, éviter le débordement, et renvoyer un double correct.","starterCode":"using System;\n\npublic class Statistics\n{\n    public static double Average(int[] numbers)\n    {\n        int sum = 0;\n        for (int i = 0; i <= numbers.Length; i++)\n        {\n            sum += numbers[i];\n        }\n        return sum / numbers.Length;\n    }\n}","solution":"using System;\n\npublic class Statistics\n{\n    public static double Average(int[] numbers)\n    {\n        if (numbers == null || numbers.Length == 0) return 0;\n        long sum = 0;\n        for (int i = 0; i < numbers.Length; i++)\n            sum += numbers[i];\n        return (double)sum / numbers.Length;\n    }\n}","tests":[{"input":"Average(new[] {2, 4, 6})","expected":"4.0"},{"input":"Average(new int[] {})","expected":"0"},{"input":"Average(null)","expected":"0"},{"input":"Average(new[] {1, 2})","expected":"1.5"}],"explanation":"Trois bugs : (1) `i <= Length` provoque un IndexOutOfRange (il faut `<`) ; (2) pas de protection null/vide (division par zéro) ; (3) division entière qui tronque (caster en double). On utilise long pour éviter le débordement.","difficulty":"medium"},
  {"category":"C#","subcategory":"Reliability","type":"code","language":"csharp","prompt":"Complétez la classe `ShoppingCart` : ajouter un article (nom + prix), retirer par nom, calculer le total. Ajouter un nom null/vide ou un prix négatif doit lever ArgumentException ; retirer un article inexistant ne doit pas planter (renvoyer false).","starterCode":"using System;\nusing System.Collections.Generic;\n\npublic class ShoppingCart\n{\n    private readonly Dictionary<string, decimal> _items = new Dictionary<string, decimal>();\n\n    public void Add(string name, decimal price) { /* TODO */ }\n    public bool Remove(string name) { throw new NotImplementedException(); }\n    public decimal Total() { throw new NotImplementedException(); }\n}","solution":"using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\npublic class ShoppingCart\n{\n    private readonly Dictionary<string, decimal> _items = new Dictionary<string, decimal>();\n\n    public void Add(string name, decimal price)\n    {\n        if (string.IsNullOrWhiteSpace(name))\n            throw new ArgumentException(\"Nom obligatoire\", nameof(name));\n        if (price < 0)\n            throw new ArgumentException(\"Prix négatif interdit\", nameof(price));\n        _items[name] = price;\n    }\n\n    public bool Remove(string name)\n    {\n        if (string.IsNullOrWhiteSpace(name)) return false;\n        return _items.Remove(name);\n    }\n\n    public decimal Total() => _items.Values.Sum();\n}","tests":[{"input":"Add(\"Pomme\", 2.5m); Total()","expected":"2.5"},{"input":"Add(\"Pain\", 1m); Remove(\"Pain\"); Total()","expected":"0"},{"input":"Remove(\"Inexistant\")","expected":"false"},{"input":"Add(\"\", 1m)","expected":"ArgumentException"}],"explanation":"La fiabilité = valider les entrées et ne pas planter sur les cas limites. Dictionary.Remove renvoie déjà un bool indiquant si la clé existait, ce qui évite tout KeyNotFoundException.","difficulty":"medium"}
];

const ASPNET_MCQ = [
  {"category":"ASP.NET Core","subcategory":"Design","type":"mcq","question":"Vous enregistrez un DbContext EF Core dans le conteneur DI. Quelle durée de vie est recommandée pour une application web standard ?","code":"builder.Services.???<AppDbContext>();","options":["AddSingleton","AddScoped","AddTransient","Peu importe, EF Core gère seul son cycle de vie"],"correctIndex":1,"explanation":"AddScoped crée une instance par requête HTTP. Recommandé pour DbContext car il n'est pas thread-safe et doit être isolé par requête. C'est d'ailleurs le défaut de AddDbContext.","difficulty":"easy"},
  {"category":"ASP.NET Core","subcategory":"Design","type":"mcq","question":"Que se passe-t-il si vous injectez un service Scoped dans un service Singleton en environnement de développement ?","code":"builder.Services.AddSingleton<ICache, Cache>();\nbuilder.Services.AddScoped<IRepo, Repo>();\n// Cache dépend de IRepo dans son constructeur","options":["Le service Scoped est correctement recréé à chaque requête","Une InvalidOperationException est levée à la résolution (captive dependency)","Le service Singleton devient automatiquement Scoped","Rien, c'est une pratique recommandée"],"correctIndex":1,"explanation":"C'est le piège de la 'captive dependency'. Le Scoped serait capturé au cycle de vie du Singleton. La validation du scope (activée par défaut en Development) lève une InvalidOperationException.","difficulty":"medium"},
  {"category":"ASP.NET Core","subcategory":"Design","type":"mcq","question":"Dans une Web API REST, pourquoi exposer un DTO plutôt que l'entité de base de données directement ?","code":null,"options":["Pour améliorer les performances des requêtes SQL","Pour découpler le contrat de l'API du modèle de persistance et éviter d'exposer des champs sensibles","Parce qu'Entity Framework interdit de sérialiser ses entités","Pour forcer l'utilisation de minimal APIs"],"correctIndex":1,"explanation":"Un DTO découple le contrat public de la structure interne de la base : évite d'exposer des champs sensibles, prévient l'over-posting et permet de faire évoluer le schéma sans casser les clients.","difficulty":"easy"},
  {"category":"ASP.NET Core","subcategory":"Design","type":"mcq","question":"Quel attribut permet de lier le corps JSON d'une requête HTTP à un paramètre de l'action ?","code":"public IActionResult Create([???] ProductDto dto) { ... }","options":["[FromQuery]","[FromRoute]","[FromBody]","[FromHeader]"],"correctIndex":2,"explanation":"[FromBody] lie le corps de la requête (JSON) au paramètre. Dans un contrôleur [ApiController], il est même implicite pour les types complexes.","difficulty":"easy"},
  {"category":"ASP.NET Core","subcategory":"Design","type":"mcq","question":"Quel code de statut HTTP est le plus approprié après la création réussie d'une ressource via POST ?","code":"return CreatedAtAction(nameof(GetById), new { id = product.Id }, product);","options":["200 OK","201 Created","204 No Content","202 Accepted"],"correctIndex":1,"explanation":"201 Created indique qu'une nouvelle ressource a été créée. CreatedAtAction retourne 201 et ajoute un en-tête Location pointant vers la ressource.","difficulty":"easy"},
  {"category":"ASP.NET Core","subcategory":"Design","type":"mcq","question":"Quelle est la différence entre IActionResult et ActionResult<T> comme type de retour d'une action ?","code":"public ActionResult<Product> Get(int id) { ... }","options":["Aucune, ce sont des alias","ActionResult<T> permet de retourner soit un type T, soit un résultat HTTP, et améliore la documentation/inférence du type","IActionResult est obsolète depuis .NET 6","ActionResult<T> empêche de retourner NotFound()"],"correctIndex":1,"explanation":"ActionResult<T> permet de retourner directement T (200) OU un IActionResult comme NotFound(). Cela documente mieux la réponse pour Swagger/OpenAPI tout en gardant la flexibilité.","difficulty":"medium"},
  {"category":"ASP.NET Core","subcategory":"Design","type":"mcq","question":"Avec l'attribut [ApiController], que se passe-t-il automatiquement quand le ModelState est invalide ?","code":"[ApiController]\n[Route(\"api/[controller]\")]\npublic class ProductsController : ControllerBase { ... }","options":["Rien, il faut vérifier ModelState.IsValid manuellement","Une réponse 400 Bad Request avec les détails de validation (ProblemDetails) est retournée automatiquement","L'action s'exécute quand même mais log un avertissement","Une exception est levée et renvoie un 500"],"correctIndex":1,"explanation":"[ApiController] active la validation automatique : si ModelState est invalide, ASP.NET Core renvoie un 400 ValidationProblemDetails, sans avoir à tester ModelState.IsValid.","difficulty":"medium"},
  {"category":"ASP.NET Core","subcategory":"Design","type":"mcq","question":"Dans un minimal API, comment lire la chaîne de connexion depuis appsettings.json ?","code":"// appsettings.json : \"ConnectionStrings\": { \"Default\": \"...\" }","options":["builder.Configuration.GetConnectionString(\"Default\")","builder.Services.GetSection(\"Default\")","Environment.GetEnvironmentVariable(\"Default\")","builder.AppSettings[\"Default\"]"],"correctIndex":0,"explanation":"GetConnectionString(\"Default\") lit Configuration[\"ConnectionStrings:Default\"]. La configuration fusionne appsettings.json, variables d'environnement, secrets, etc. par ordre de priorité.","difficulty":"easy"},
  {"category":"ASP.NET Core","subcategory":"Reliability","type":"mcq","question":"Dans cette configuration du pipeline, pourquoi l'authentification échoue-t-elle systématiquement (l'utilisateur reste anonyme) ?","code":"app.UseRouting();\napp.UseAuthorization();\napp.UseAuthentication();\napp.MapControllers();","options":["Il manque app.UseCors()","UseAuthentication doit être appelé AVANT UseAuthorization","UseRouting est inutile et bloque l'authentification","MapControllers doit être appelé en premier"],"correctIndex":1,"explanation":"L'ordre du pipeline est critique. UseAuthentication (identifie l'utilisateur) doit précéder UseAuthorization (vérifie ses droits). Inversés, l'utilisateur est toujours anonyme.","difficulty":"medium"},
  {"category":"ASP.NET Core","subcategory":"Reliability","type":"mcq","question":"Un middleware personnalisé n'appelle pas await next(context). Quelle conséquence ?","code":"app.Use(async (context, next) =>\n{\n    context.Response.StatusCode = 403;\n    // pas d'appel à next\n});","options":["Les middlewares suivants et l'endpoint s'exécutent quand même","Le pipeline est court-circuité : aucun middleware suivant ni l'endpoint ne s'exécute","Une exception NullReferenceException est levée","La requête est automatiquement renvoyée au début du pipeline"],"correctIndex":1,"explanation":"Appeler next() passe la main au middleware suivant. Ne pas l'appeler court-circuite le pipeline : la réponse déjà écrite (403) est renvoyée et rien d'autre ne s'exécute.","difficulty":"medium"},
  {"category":"ASP.NET Core","subcategory":"Reliability","type":"mcq","question":"Quel format standardisé ASP.NET Core utilise-t-il pour renvoyer les erreurs HTTP de manière interopérable (RFC 7807) ?","code":"return Problem(detail: \"Solde insuffisant\", statusCode: 409);","options":["Un objet ProblemDetails (type, title, status, detail)","Une simple chaîne de caractères dans le corps","Un objet Exception sérialisé entièrement","Un code HTML d'erreur"],"correctIndex":0,"explanation":"ProblemDetails (RFC 7807) standardise les erreurs avec type, title, status, detail, instance. Problem() et UseExceptionHandler le produisent automatiquement.","difficulty":"medium"},
  {"category":"ASP.NET Core","subcategory":"Reliability","type":"mcq","question":"Pourquoi est-il important d'utiliser async/await avec des appels I/O (BDD, HTTP) dans les actions d'un contrôleur ?","code":"public async Task<ActionResult<Product>> Get(int id)\n{\n    var product = await _db.Products.FindAsync(id);\n    return product is null ? NotFound() : product;\n}","options":["Cela rend chaque requête individuelle plus rapide pour l'utilisateur","Cela libère le thread pendant l'attente I/O, améliorant la scalabilité sous forte charge","C'est obligatoire, le code ne compile pas sinon","Cela évite d'avoir à gérer les exceptions"],"correctIndex":1,"explanation":"async/await ne rend pas une requête isolée plus rapide, mais libère le thread du pool pendant l'attente I/O, améliorant le débit et évitant l'épuisement du thread pool sous charge.","difficulty":"hard"}
];

const EF_MCQ = [
  {"category":"Entity Framework","subcategory":"Fetching","type":"mcq","question":"Quelle méthode permet de charger explicitement une entité liée dans la même requête SQL (eager loading) ?","code":"var orders = context.Orders\n    .______(o => o.Customer)\n    .ToList();","options":["Include","Load","Attach","Reference"],"correctIndex":0,"explanation":"Include() réalise l'eager loading : EF Core génère un JOIN pour charger l'entité liée dans la même requête. ThenInclude() charge un niveau imbriqué.","difficulty":"easy"},
  {"category":"Entity Framework","subcategory":"Fetching","type":"mcq","question":"Quelle est la différence principale entre le lazy loading et l'eager loading en EF Core ?","code":null,"options":["Le lazy loading charge les données liées seulement au premier accès à la navigation property, l'eager loading les charge dès la requête initiale","Le lazy loading charge tout immédiatement, l'eager loading attend","Les deux chargent au même moment, seule la syntaxe diffère","Le lazy loading ne fonctionne qu'avec AsNoTracking"],"correctIndex":0,"explanation":"Le lazy loading déclenche une requête SQL au moment où l'on accède à la propriété de navigation. L'eager loading (Include) charge les données dès la requête principale. Le lazy mal maîtrisé cause le N+1.","difficulty":"medium"},
  {"category":"Entity Framework","subcategory":"Fetching","type":"mcq","question":"Que fait AsNoTracking() sur une requête EF Core ?","code":"var products = context.Products\n    .AsNoTracking()\n    .ToList();","options":["Désactive le suivi des changements par le change tracker, améliorant les performances en lecture seule","Empêche toute requête vers la base de données","Force le rechargement des entités déjà en cache","Active la validation des contraintes avant lecture"],"correctIndex":0,"explanation":"AsNoTracking() indique de ne pas suivre l'état des entités retournées : idéal en lecture seule (moins de mémoire, plus rapide). En contrepartie, SaveChanges() ne persistera pas de modifications.","difficulty":"easy"},
  {"category":"Entity Framework","subcategory":"Fetching","type":"mcq","question":"À quel moment une requête IQueryable est-elle réellement exécutée sur la base (exécution différée) ?","code":"var query = context.Users.Where(u => u.IsActive); // (1)\nvar list = query.ToList();                          // (2)","options":["À la ligne (2), lors de l'énumération (ToList) ; la ligne (1) ne fait que construire l'expression","À la ligne (1), dès l'appel à Where","Au moment de la création du DbContext","Jamais tant que SaveChanges n'est pas appelé"],"correctIndex":0,"explanation":"IQueryable repose sur l'exécution différée : la requête n'est traduite en SQL qu'au moment de l'énumération (ToList, foreach, First, Count...). Avant, on ne fait que composer l'arbre d'expression.","difficulty":"medium"},
  {"category":"Entity Framework","subcategory":"Fetching","type":"mcq","question":"Quelle est la conséquence d'appeler AsEnumerable() (ou ToList()) trop tôt, avant un Where() ?","code":"var result = context.Orders\n    .AsEnumerable()\n    .Where(o => o.Total > 100)\n    .ToList();","options":["Le filtre Where s'exécute en mémoire côté client après avoir chargé TOUTES les commandes","Le filtre est traduit en SQL et exécuté côté base de données","Cela provoque une exception à l'exécution","EF Core optimise automatiquement et déplace le Where dans le SQL"],"correctIndex":0,"explanation":"Dès qu'on bascule en IEnumerable (AsEnumerable/ToList), les opérateurs suivants s'exécutent en mémoire (LINQ to Objects). Toutes les commandes sont rapatriées puis filtrées : très inefficace.","difficulty":"medium"},
  {"category":"Entity Framework","subcategory":"Fetching","type":"mcq","question":"Quel est l'avantage d'une projection avec Select par rapport au chargement de l'entité complète ?","code":"var dtos = context.Users\n    .Select(u => new UserDto { Id = u.Id, Name = u.Name })\n    .ToList();","options":["Seules les colonnes nécessaires sont requêtées en SQL et les résultats projetés ne sont pas suivis par le change tracker","La projection charge toujours toutes les colonnes mais les masque ensuite","Select empêche obligatoirement l'utilisation d'Include dans la même requête","Une projection est plus lente car elle crée des objets supplémentaires"],"correctIndex":0,"explanation":"Select génère un SQL qui ne sélectionne que les colonnes utiles. De plus, les types projetés ne sont pas suivis par le change tracker, comme un AsNoTracking implicite.","difficulty":"medium"},
  {"category":"Entity Framework","subcategory":"Fetching","type":"mcq","question":"Quel code illustre le problème N+1 et comment le corriger ?","code":"var blogs = context.Blogs.ToList();\nforeach (var blog in blogs)\n{\n    Console.WriteLine(blog.Posts.Count); // lazy loading\n}","options":["C'est un N+1 : 1 requête pour les blogs + 1 par blog pour ses Posts ; on corrige avec context.Blogs.Include(b => b.Posts)","C'est optimal, EF Core regroupe automatiquement toutes les requêtes","On corrige uniquement avec AsNoTracking()","Le problème vient de ToList() qu'il faut retirer"],"correctIndex":0,"explanation":"N+1 : une requête initiale (N blogs) déclenche une requête par blog pour ses Posts via lazy loading. La solution est l'eager loading avec Include(b => b.Posts) pour tout charger en une requête.","difficulty":"hard"},
  {"category":"Entity Framework","subcategory":"Relationship","type":"mcq","question":"Comment configure-t-on une relation one-to-many entre Blog et Post avec l'API Fluent ?","code":"modelBuilder.Entity<Post>()\n    .HasOne(p => p.Blog)\n    .________(b => b.Posts)\n    .HasForeignKey(p => p.BlogId);","options":["WithMany","WithOne","HasMany","WithForeignKey"],"correctIndex":0,"explanation":"Une relation one-to-many se déclare avec HasOne(...).WithMany(...). Côté Post : HasOne(p => p.Blog), côté Blog : WithMany(b => b.Posts), et HasForeignKey précise la clé étrangère.","difficulty":"medium"},
  {"category":"Entity Framework","subcategory":"Relationship","type":"mcq","question":"Comment EF Core gère-t-il une relation many-to-many depuis EF Core 5+ ?","code":"public class Student { public List<Course> Courses { get; set; } }\npublic class Course { public List<Student> Students { get; set; } }","options":["EF Core crée et gère automatiquement une table de jointure implicite, sans classe d'entité dédiée nécessaire","Il faut obligatoirement créer manuellement une entité de jointage explicite","Les relations many-to-many ne sont pas supportées","Il faut déclarer deux relations one-to-one"],"correctIndex":0,"explanation":"Depuis EF Core 5.0, le many-to-many est détecté par convention : une collection de chaque côté suffit. EF Core génère une table de jointure implicite. On peut définir une entité de jointage explicite si on a besoin d'attributs supplémentaires.","difficulty":"medium"},
  {"category":"Entity Framework","subcategory":"Relationship","type":"mcq","question":"Quelle affirmation est correcte concernant Fluent API et Data Annotations ?","code":null,"options":["La Fluent API offre plus de possibilités et, en cas de conflit, prend le dessus sur les Data Annotations","Les Data Annotations sont prioritaires sur la Fluent API en cas de conflit","On ne peut jamais combiner les deux approches","La Fluent API ne peut configurer que les clés primaires"],"correctIndex":0,"explanation":"Les Data Annotations sont simples mais limitées. La Fluent API (OnModelCreating) est plus expressive (clés composites, cascade...). En cas de conflit, la Fluent API l'emporte.","difficulty":"medium"},
  {"category":"Entity Framework","subcategory":"Relationship","type":"mcq","question":"Quel comportement de suppression en cascade EF Core applique-t-il par défaut sur une relation obligatoire (FK non nullable) ?","code":"modelBuilder.Entity<Blog>()\n    .HasMany(b => b.Posts)\n    .WithOne(p => p.Blog)\n    .OnDelete(DeleteBehavior.Cascade);","options":["Cascade : supprimer le parent (Blog) supprime automatiquement les enfants (Posts)","Restrict : la suppression du parent est toujours bloquée","SetNull : la clé étrangère des enfants passe à NULL","Aucune action : les enfants sont conservés avec une FK invalide"],"correctIndex":0,"explanation":"Pour une relation requise (FK non nullable), EF Core applique par défaut DeleteBehavior.Cascade. Pour une relation optionnelle (FK nullable), le défaut est ClientSetNull/SetNull.","difficulty":"hard"}
];

const ANGULAR_MCQ = [
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Quel hook de cycle de vie est appelé une seule fois, juste après l'initialisation des propriétés liées par data binding ?","code":null,"options":["ngOnChanges","ngOnInit","ngAfterViewInit","ngDoCheck"],"correctIndex":1,"explanation":"ngOnInit est appelé une fois après le premier ngOnChanges, une fois les @Input initialisés. Idéal pour la logique d'initialisation (appels HTTP, abonnements).","difficulty":"easy"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Dans un template Angular, quelle syntaxe correspond au property binding (liaison de propriété) ?","code":"<img ... src=\"...\">","options":["{{ imageUrl }}","[src]=\"imageUrl\"","(src)=\"imageUrl\"","[(src)]=\"imageUrl\""],"correctIndex":1,"explanation":"Les crochets [ ] désignent le property binding (composant vers DOM). {{ }} = interpolation, ( ) = event binding, [( )] = two-way binding.","difficulty":"easy"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Que permet la syntaxe [(ngModel)] dans un formulaire template-driven ?","code":"<input [(ngModel)]=\"username\">","options":["Uniquement d'afficher la valeur (lecture seule)","Le two-way data binding : synchroniser la propriété et le champ dans les deux sens","D'écouter uniquement l'événement input","De déclarer un formulaire réactif"],"correctIndex":1,"explanation":"[(ngModel)] combine [ngModel] et (ngModelChange). Toute saisie met à jour la propriété et inversement. Nécessite l'import de FormsModule.","difficulty":"easy"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Avec le nouveau control flow d'Angular 17+, quel bloc remplace *ngFor et quelle particularité lui est imposée ?","code":"@for (item of items; track item.id) {\n  <li>{{ item.name }}</li>\n}","options":["@each, et track est interdit","@for, et track est obligatoire","@loop, et track est optionnel","@foreach, et l'index est obligatoire"],"correctIndex":1,"explanation":"@for remplace *ngFor depuis Angular 17. La fonction track est obligatoire (contrairement à trackBy) pour optimiser le rendu. @for supporte aussi un bloc @empty.","difficulty":"medium"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Comment lit-on la valeur d'un signal en Angular 16+ ?","code":"count = signal(0);","options":["this.count","this.count()","this.count.value","this.count.get()"],"correctIndex":1,"explanation":"Un signal se lit en l'appelant comme une fonction : count(). Pour le modifier : count.set(5) ou count.update(v => v + 1). Pas de .value ni .get().","difficulty":"medium"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Quel est le rôle de computed() dans l'API Signals d'Angular ?","code":"const count = signal(2);\nconst double = computed(() => count() * 2);","options":["Créer un signal modifiable par .set()","Créer un signal en lecture seule dérivé d'autres signals, recalculé automatiquement","Exécuter un effet de bord à chaque changement","Convertir un Observable en signal"],"correctIndex":1,"explanation":"computed() crée un signal en lecture seule dérivé d'autres signals, recalculé paresseusement et mis en cache. Les effets de bord relèvent de effect().","difficulty":"medium"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"À quoi sert le pipe async dans un template Angular ?","code":"<div>{{ data$ | async }}</div>","options":["Il transforme une chaîne en majuscules","Il s'abonne automatiquement à un Observable/Promise et se désabonne à la destruction","Il force le rafraîchissement manuel du composant","Il convertit un tableau en Observable"],"correctIndex":1,"explanation":"Le pipe async s'abonne à un Observable, retourne la dernière valeur émise, et se désabonne automatiquement à la destruction du composant. Évite les fuites mémoire.","difficulty":"medium"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Dans une chaîne RxJS, quel opérateur transforme chaque valeur émise par un Observable ?","code":"source$.pipe(\n  map(x => x * 2)\n).subscribe(console.log);","options":["filter","map","tap","subscribe"],"correctIndex":1,"explanation":"map applique une transformation à chaque valeur émise. filter filtre, tap exécute un effet de bord sans modifier le flux, subscribe déclenche l'exécution.","difficulty":"easy"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Comment déclare-t-on qu'une propriété d'un composant reçoit une donnée depuis son composant parent ?","code":null,"options":["@Output() value: string;","@Input() value: string;","@ViewChild() value: string;","@HostBinding() value: string;"],"correctIndex":1,"explanation":"@Input() reçoit des données du parent (parent -> enfant). @Output() envoie des événements vers le parent. Template parent : <app-child [value]=\"data\">.","difficulty":"easy"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Quelle affirmation décrit correctement un composant standalone (par défaut en v17+) ?","code":"@Component({\n  selector: 'app-foo',\n  standalone: true,\n  imports: [CommonModule],\n  template: '...'\n})\nexport class FooComponent {}","options":["Il doit obligatoirement être déclaré dans le tableau declarations d'un NgModule","Il gère ses propres dépendances via la propriété imports et n'a pas besoin de NgModule","Il ne peut pas utiliser de directives ni de pipes","Il est réservé aux services injectables"],"correctIndex":1,"explanation":"Un composant standalone déclare ses dépendances dans sa propre propriété imports, sans NgModule. Cela supprime le boilerplate des modules. Mode par défaut depuis Angular 17.","difficulty":"medium"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Comment rend-on un service injectable disponible en singleton dans toute l'application sans le déclarer dans un module ?","code":null,"options":["@Injectable({ providedIn: 'root' })","@Component({ providers: [] })","@NgModule({ declarations: [] })","@Injectable({ standalone: true })"],"correctIndex":0,"explanation":"@Injectable({ providedIn: 'root' }) enregistre le service au niveau de l'injecteur racine : singleton accessible partout, et tree-shakable s'il n'est pas utilisé.","difficulty":"medium"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Quelle interface un guard de route implémente-t-il pour autoriser ou bloquer l'accès à une route avant son activation ?","code":null,"options":["CanDeactivate","CanActivate","Resolve","CanLoad"],"correctIndex":1,"explanation":"CanActivate détermine si une route peut être activée (souvent pour l'authentification). Retourne boolean, UrlTree, ou Observable/Promise. CanDeactivate contrôle la sortie.","difficulty":"medium"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Quelle différence majeure distingue un formulaire reactive d'un formulaire template-driven ?","code":"this.form = new FormGroup({\n  email: new FormControl('')\n});","options":["Le reactive définit la structure du formulaire dans la classe TypeScript, le template-driven dans le HTML via ngModel","Le reactive ne supporte aucune validation","Le template-driven nécessite l'import de ReactiveFormsModule","Les deux sont strictement identiques, seul le nom change"],"correctIndex":0,"explanation":"Les formulaires reactive définissent le modèle (FormGroup/FormControl) dans la classe TS (ReactiveFormsModule), plus testables. Les template-driven s'appuient sur ngModel dans le HTML (FormsModule).","difficulty":"medium"},
  {"category":"Angular","subcategory":"Language knowledge","type":"mcq","question":"Quel effet a la stratégie ChangeDetectionStrategy.OnPush sur un composant ?","code":"@Component({\n  selector: 'app-item',\n  changeDetection: ChangeDetectionStrategy.OnPush,\n  template: '...'\n})\nexport class ItemComponent {}","options":["Le composant n'est jamais vérifié","Le composant n'est revérifié que si une référence d'@Input change, un événement survient, ou un Observable lié via async émet","Le composant est vérifié deux fois plus souvent","Elle désactive complètement la détection de changement de l'application"],"correctIndex":1,"explanation":"OnPush optimise : Angular ne relance la détection que si une référence d'@Input change (comparaison par référence), si un événement survient, ou si un async émet. Réduit les vérifications inutiles.","difficulty":"hard"}
];

const JS_MCQ = [
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Que renvoie l'expression suivante ?","code":"console.log(0 == '0', 0 === '0', null == undefined);","options":["true false true","true true true","false false true","true false false"],"correctIndex":0,"explanation":"Avec == il y a coercition : 0 == '0' convertit '0' en 0 (true). Avec === aucune conversion (number != string -> false). null == undefined vaut true (égaux en égalité lâche).","difficulty":"junior"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Que renvoie typeof null ?","code":"console.log(typeof null);","options":["\"null\"","\"object\"","\"undefined\"","\"number\""],"correctIndex":1,"explanation":"typeof null vaut \"object\". C'est un bug historique de JavaScript jamais corrigé pour ne pas casser le code existant.","difficulty":"junior"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Quel sera le résultat du hoisting dans ce code ?","code":"console.log(a);\nvar a = 5;\nconsole.log(b);\nlet b = 10;","options":["undefined puis ReferenceError","5 puis 10","undefined puis undefined","ReferenceError immédiate"],"correctIndex":0,"explanation":"var a est hissée et initialisée à undefined (1er log = undefined). let b est hissée mais reste en 'temporal dead zone' : y accéder avant sa déclaration lève une ReferenceError.","difficulty":"intermediaire"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Que va afficher cette closure dans une boucle ?","code":"for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}","options":["0 1 2","3 3 3","0 0 0","undefined undefined undefined"],"correctIndex":1,"explanation":"Avec var, une seule variable i partagée (scope de fonction). Les callbacks s'exécutent après la boucle, quand i vaut 3. Avec let, chaque itération créerait une nouvelle liaison (0 1 2).","difficulty":"intermediaire"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Dans quel ordre ces messages s'affichent-ils (event loop) ?","code":"console.log('A');\nsetTimeout(() => console.log('B'), 0);\nPromise.resolve().then(() => console.log('C'));\nconsole.log('D');","options":["A B C D","A D C B","A D B C","A C D B"],"correctIndex":1,"explanation":"Le code synchrone d'abord : A puis D. Puis les microtâches (Promises) sont vidées avant les macrotâches (setTimeout) : C avant B. Résultat : A D C B.","difficulty":"intermediaire"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Que renvoie ce reduce ?","code":"const r = [1, 2, 3, 4].reduce((acc, n) => acc + n, 0);\nconsole.log(r);","options":["[1, 2, 3, 4]","10","0","24"],"correctIndex":1,"explanation":"reduce accumule une valeur unique. Avec l'initiale 0 : 0+1+2+3+4 = 10.","difficulty":"junior"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Que vaut la variable c après cette destructuration avec valeur par défaut ?","code":"const { a, b, c = 9 } = { a: 1, b: 2 };\nconsole.log(c);","options":["undefined","2","9","0"],"correctIndex":2,"explanation":"c n'existe pas dans l'objet source (undefined), donc la valeur par défaut 9 s'applique. Une valeur par défaut ne s'applique qu'en cas d'undefined (pas pour null ou 0).","difficulty":"junior"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Que produit l'opérateur spread ici ?","code":"const a = [1, 2];\nconst b = [...a, 3, ...a];\nconsole.log(b);","options":["[1, 2, 3, 1, 2]","[[1,2], 3, [1,2]]","[1, 2, 3]","[6]"],"correctIndex":0,"explanation":"Le spread ...a déballe les éléments du tableau. On obtient 1, 2, puis 3, puis à nouveau 1, 2 : soit [1, 2, 3, 1, 2].","difficulty":"junior"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"Que vaut this dans la méthode appelée de cette façon ?","code":"const obj = {\n  name: 'X',\n  greet() { return this.name; }\n};\nconst fn = obj.greet;\nconsole.log(fn());","options":["'X'","undefined (en mode strict) ou erreur","'fn'","null"],"correctIndex":1,"explanation":"this dépend de COMMENT la fonction est appelée. Détachée et appelée comme fn(), this n'est plus obj. En mode strict this = undefined (TypeError) ; sinon c'est l'objet global.","difficulty":"intermediaire"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"En TypeScript, quelle signature de fonction générique renvoie un élément du même type que celui passé ?","code":null,"options":["function identity(x: any): any","function identity<T>(x: T): T","function identity(x: T): T","function identity<T>(x: any): T"],"correctIndex":1,"explanation":"Un générique <T> capture le type de l'argument et le réutilise pour le retour, préservant l'information de type (contrairement à any qui la perd).","difficulty":"intermediaire"},
  {"category":"JavaScript","subcategory":"Language knowledge","type":"mcq","question":"En TypeScript, que représente le type union string | number pour la variable val ?","code":"let val: string | number;","options":["val doit être à la fois une string ET un number","val peut être soit une string soit un number","val est forcément une string","val est de type any"],"correctIndex":1,"explanation":"Un type union (avec |) autorise la valeur à appartenir à l'un OU l'autre des types. Pour utiliser des méthodes spécifiques, il faut affiner le type (narrowing) avec typeof.","difficulty":"junior"},
  {"category":"JavaScript","subcategory":"Reliability","type":"mcq","question":"Pourquoi NaN === NaN renvoie-t-il false, et comment tester de façon fiable qu'une valeur est NaN ?","code":"console.log(NaN === NaN);","options":["C'est false ; utiliser Number.isNaN(x) pour tester","C'est true ; pas besoin de fonction dédiée","C'est false ; utiliser x == NaN pour tester","C'est une erreur de syntaxe"],"correctIndex":0,"explanation":"NaN est la seule valeur non égale à elle-même (false). Pour tester de façon fiable : Number.isNaN(x), qui ne fait pas de coercition contrairement à l'ancien isNaN global.","difficulty":"intermediaire"}
];

const JS_CODE = [
  {"category":"JavaScript","subcategory":"Problem solving","type":"code","language":"javascript","prompt":"Écris une fonction qui calcule la somme de tous les nombres d'un tableau. Si le tableau est vide, elle doit renvoyer 0.","starterCode":"function sumArray(numbers) {\n  // Additionne tous les éléments du tableau\n}","solution":"function sumArray(numbers) {\n  return numbers.reduce((acc, n) => acc + n, 0);\n}","tests":[{"input":"[1, 2, 3, 4]","expected":"10"},{"input":"[]","expected":"0"},{"input":"[-5, 5, 10]","expected":"10"}],"functionName":"sumArray","explanation":"reduce parcourt le tableau en accumulant un total. La valeur initiale 0 garantit le bon résultat même pour un tableau vide.","difficulty":"junior"},
  {"category":"JavaScript","subcategory":"Problem solving","type":"code","language":"javascript","prompt":"Écris une fonction qui inverse l'ordre des caractères d'une chaîne et renvoie la chaîne inversée.","starterCode":"function reverseString(str) {\n  // Renvoie la chaîne à l'envers\n}","solution":"function reverseString(str) {\n  return str.split('').reverse().join('');\n}","tests":[{"input":"\"hello\"","expected":"\"olleh\""},{"input":"\"a\"","expected":"\"a\""},{"input":"\"\"","expected":"\"\""}],"functionName":"reverseString","explanation":"split('') transforme la chaîne en tableau de caractères, reverse() inverse l'ordre, et join('') reconstruit la chaîne.","difficulty":"junior"},
  {"category":"JavaScript","subcategory":"Problem solving","type":"code","language":"javascript","prompt":"Écris une fonction FizzBuzz qui, pour un entier n, renvoie un tableau de 1 à n où chaque multiple de 3 est \"Fizz\", chaque multiple de 5 est \"Buzz\", chaque multiple de 3 et 5 est \"FizzBuzz\". Les autres restent des nombres.","starterCode":"function fizzBuzz(n) {\n  // Renvoie un tableau de 1 à n avec les remplacements\n}","solution":"function fizzBuzz(n) {\n  const result = [];\n  for (let i = 1; i <= n; i++) {\n    if (i % 15 === 0) result.push('FizzBuzz');\n    else if (i % 3 === 0) result.push('Fizz');\n    else if (i % 5 === 0) result.push('Buzz');\n    else result.push(i);\n  }\n  return result;\n}","tests":[{"input":"5","expected":"[1, 2, \"Fizz\", 4, \"Buzz\"]"},{"input":"3","expected":"[1, 2, \"Fizz\"]"},{"input":"1","expected":"[1]"}],"functionName":"fizzBuzz","explanation":"On teste d'abord le multiple de 15 (3 et 5) avant 3 et 5 isolés, sinon \"FizzBuzz\" ne serait jamais atteint.","difficulty":"intermediaire"},
  {"category":"JavaScript","subcategory":"Problem solving","type":"code","language":"javascript","prompt":"Écris une fonction qui compte les occurrences de chaque élément d'un tableau et renvoie un objet associant chaque valeur à son nombre d'apparitions.","starterCode":"function countOccurrences(items) {\n  // Renvoie un objet { valeur: nombre d'occurrences }\n}","solution":"function countOccurrences(items) {\n  return items.reduce((counts, item) => {\n    counts[item] = (counts[item] || 0) + 1;\n    return counts;\n  }, {});\n}","tests":[{"input":"[\"a\", \"b\", \"a\", \"c\", \"b\", \"a\"]","expected":"{ a: 3, b: 2, c: 1 }"},{"input":"[]","expected":"{}"},{"input":"[1, 1, 1]","expected":"{ \"1\": 3 }"}],"functionName":"countOccurrences","explanation":"On utilise un objet accumulateur. (counts[item] || 0) + 1 démarre à 1 si la clé n'existe pas, sinon incrémente.","difficulty":"intermediaire"},
  {"category":"JavaScript","subcategory":"Problem solving","type":"code","language":"javascript","prompt":"Écris une fonction qui supprime les doublons d'un tableau tout en conservant l'ordre d'apparition des éléments.","starterCode":"function removeDuplicates(items) {\n  // Renvoie un nouveau tableau sans doublons\n}","solution":"function removeDuplicates(items) {\n  return [...new Set(items)];\n}","tests":[{"input":"[1, 2, 2, 3, 3, 3, 4]","expected":"[1, 2, 3, 4]"},{"input":"[\"a\", \"b\", \"a\"]","expected":"[\"a\", \"b\"]"},{"input":"[]","expected":"[]"}],"functionName":"removeDuplicates","explanation":"Un Set ne stocke que des valeurs uniques et préserve l'ordre d'insertion. Le spread [...set] le reconvertit en tableau.","difficulty":"junior"}
];

const CSS_MCQ = [
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Avec `box-sizing: border-box`, quelle est la largeur totale rendue de cet élément à l'écran ?","code":".box {\n  width: 200px;\n  padding: 20px;\n  border: 5px solid black;\n  box-sizing: border-box;\n}","options":["250px","230px","200px","210px"],"correctIndex":2,"explanation":"Avec border-box, la valeur de width inclut le padding et la border. La largeur rendue reste 200px (le contenu est réduit à 150px). En content-box ce serait 250px.","difficulty":"easy"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Un élément en `position: absolute` est positionné par rapport à quel élément ?","code":null,"options":["Toujours la fenêtre du navigateur (viewport)","Son ancêtre positionné le plus proche (position autre que static)","Toujours son parent direct","Le <body> du document"],"correctIndex":1,"explanation":"Un élément absolute se positionne par rapport à l'ancêtre le plus proche ayant une position != static. S'il n'en existe aucun, il se réfère au viewport. fixed, lui, se réfère toujours au viewport.","difficulty":"medium"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"En quoi `position: sticky` diffère-t-il de `fixed` ?","code":null,"options":["sticky est identique à fixed mais sans support IE","sticky se comporte comme relative puis devient fixed quand on atteint le seuil de défilement défini","sticky retire l'élément du flux dès le chargement","sticky ne fonctionne qu'en position horizontale"],"correctIndex":1,"explanation":"sticky est hybride : l'élément reste dans le flux (comme relative) jusqu'au seuil de défilement (top, bottom...), puis se fige (comme fixed) dans son conteneur parent. Un seuil est obligatoire.","difficulty":"medium"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Dans un conteneur flex en `flex-direction: row`, quelle propriété aligne les éléments le long de l'axe principal (horizontal) ?","code":".container {\n  display: flex;\n  flex-direction: row;\n}","options":["align-items","justify-content","align-content","place-self"],"correctIndex":1,"explanation":"justify-content aligne sur l'axe principal (horizontal en row). align-items aligne sur l'axe transversal (vertical en row). En flex-direction: column, les rôles s'inversent.","difficulty":"easy"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Que signifie la valeur `1fr` dans `grid-template-columns: 1fr 2fr 1fr` ?","code":".grid {\n  display: grid;\n  grid-template-columns: 1fr 2fr 1fr;\n}","options":["Une largeur fixe de 1 pixel","Une fraction de l'espace disponible : les colonnes valent 25%, 50%, 25%","100% de la largeur pour chaque colonne","1 fragment équivaut à 16px comme rem"],"correctIndex":1,"explanation":"L'unité fr répartit l'espace LIBRE proportionnellement. Avec 1fr 2fr 1fr (4 parts), les colonnes occupent 1/4, 2/4, 1/4 de l'espace, soit 25%, 50%, 25%.","difficulty":"medium"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Parmi ces sélecteurs, lequel a la spécificité la plus forte ?","code":"a) #menu\nb) .nav .item\nc) ul li a\nd) a:hover","options":["#menu","b) .nav .item","c) ul li a","d) a:hover"],"correctIndex":0,"explanation":"Spécificité (ID, classe, type) : #menu = (1,0,0) ; .nav .item = (0,2,0) ; ul li a = (0,0,3) ; a:hover = (0,1,1). Un seul ID l'emporte sur n'importe quel nombre de classes ou de types.","difficulty":"medium"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Quelle est la différence entre une pseudo-classe et un pseudo-élément ?","code":"a:hover { color: red; }\np::first-line { font-weight: bold; }","options":["Aucune, : et :: sont interchangeables partout","La pseudo-classe (:) cible un état de l'élément ; le pseudo-élément (::) cible/crée une sous-partie de l'élément","Le pseudo-élément cible un état, la pseudo-classe une sous-partie","Les pseudo-éléments ne fonctionnent qu'avec JavaScript"],"correctIndex":1,"explanation":"Une pseudo-classe (:hover, :focus) cible un état/position. Un pseudo-élément (::before, ::after, ::first-line) stylise ou génère une partie de l'élément. La syntaxe moderne distingue : et ::.","difficulty":"easy"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Quelle est la différence entre les unités `em` et `rem` ?","code":null,"options":["em est relatif au font-size de l'élément parent/courant, rem est relatif à celui de l'élément racine <html>","em et rem sont tous deux relatifs à la racine","rem vaut toujours 16px, em toujours 12px","em est une unité absolue, rem une unité relative"],"correctIndex":0,"explanation":"em est relatif au font-size du contexte courant (effet de cumul imbriqué possible). rem (root em) est toujours relatif au font-size de <html>, donc plus prévisible.","difficulty":"medium"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Que cible cette media query ?","code":"@media (max-width: 768px) {\n  .sidebar { display: none; }\n}","options":["Les écrans dont la largeur du viewport est strictement supérieure à 768px","Les écrans dont la largeur du viewport est inférieure ou égale à 768px","Uniquement les écrans d'exactement 768px","Les écrans de hauteur inférieure à 768px"],"correctIndex":1,"explanation":"max-width: 768px applique les règles quand la largeur du viewport est <= 768px (petits écrans). Ici la sidebar est masquée. min-width ferait l'inverse.","difficulty":"easy"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Pourquoi la boîte rouge (z-index: 9999) peut-elle s'afficher SOUS la boîte bleue ?","code":".parent {\n  position: relative;\n  z-index: 1;\n  transform: scale(1); /* crée un stacking context */\n}\n.red { position: absolute; z-index: 9999; } /* dans .parent */\n.blue { position: absolute; z-index: 2; } /* hors de .parent */","options":["z-index: 9999 est une valeur invalide","Le z-index de .red n'a d'effet qu'à l'intérieur du stacking context de .parent (z-index: 1), qui passe globalement sous .blue (z-index: 2)","Il faut ajouter position: static à .red","Les z-index supérieurs à 100 sont ignorés"],"correctIndex":1,"explanation":".parent crée un contexte d'empilement. Le z-index: 9999 de .red n'est comparé qu'aux frères DANS ce contexte. Globalement, c'est le z-index: 1 de .parent qui est comparé à .blue (z-index: 2).","difficulty":"hard"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Quelle est la différence de comportement entre `display: inline-block` et `display: block` ?","code":null,"options":["inline-block ne respecte ni width ni height, contrairement à block","inline-block s'aligne horizontalement (comme inline) tout en acceptant width, height, margins/paddings verticaux","block se place sur la même ligne que les éléments voisins","Les deux occupent toujours toute la largeur disponible"],"correctIndex":1,"explanation":"block occupe toute la largeur et provoque un retour à la ligne. inline-block ne force pas de retour à la ligne mais accepte width, height et marges verticales, contrairement à inline pur.","difficulty":"easy"},
  {"category":"CSS","subcategory":"Language knowledge","type":"mcq","question":"Quelle sera la couleur du texte `.btn`, et pourquoi ?","code":":root { --main-color: blue; }\n.card { --main-color: green; }\n.btn { color: var(--main-color, red); }\n/* HTML: <div class=\"card\"><button class=\"btn\">OK</button></div> */","options":["red, car --main-color n'existe pas sur .btn","blue, car :root a la priorité","green, car les custom properties sont héritées et .btn hérite de .card","Erreur : on ne peut pas redéfinir une variable CSS"],"correctIndex":2,"explanation":"Les custom properties sont héritées via la cascade. .btn est enfant de .card, il hérite de --main-color: green (qui surcharge :root pour cette branche). Le repli red ne sert que si la variable n'est pas définie.","difficulty":"hard"}
];

const GIT_MCQ = [
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Quelle commande permet de créer une copie locale complète d'un dépôt distant existant ?","code":null,"options":["git init","git clone <url>","git pull <url>","git fetch <url>"],"correctIndex":1,"explanation":"git clone <url> télécharge l'intégralité du dépôt (historique, branches, fichiers) et configure le remote 'origin'. git init crée un dépôt vide.","difficulty":"easy"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Que fait la commande git add sur un fichier modifié ?","code":"git add file.txt","options":["Elle crée un commit avec le fichier","Elle ajoute le fichier à la staging area (index) pour le prochain commit","Elle pousse le fichier vers le remote","Elle annule les modifications du fichier"],"correctIndex":1,"explanation":"git add place les modifications dans la staging area (index), zone intermédiaire qui prépare le prochain commit. Le commit n'est créé qu'avec git commit.","difficulty":"easy"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Quelle est la différence essentielle entre git fetch et git pull ?","code":null,"options":["fetch télécharge ET fusionne, pull télécharge seulement","fetch télécharge les changements sans modifier ta branche locale, pull fait fetch puis merge (ou rebase)","Les deux sont strictement identiques","pull fonctionne en local, fetch uniquement à distance"],"correctIndex":1,"explanation":"git fetch récupère les changements sans toucher ta branche de travail. git pull = git fetch + intégration (merge par défaut, ou rebase), modifiant la branche courante.","difficulty":"medium"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Que fait git reset --soft HEAD~1 ?","code":"git reset --soft HEAD~1","options":["Supprime le dernier commit et toutes ses modifications définitivement","Déplace HEAD au commit précédent en gardant les modifications dans la staging area","Déplace HEAD au commit précédent en désindexant les modifications","Crée un nouveau commit qui inverse le dernier"],"correctIndex":1,"explanation":"Avec --soft, seul HEAD recule : les changements restent dans la staging area, prêts à être recommittés. --mixed les désindexerait, --hard les supprimerait.","difficulty":"medium"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Quelle commande annule l'effet d'un commit déjà publié en créant un NOUVEAU commit, sans réécrire l'historique ?","code":null,"options":["git reset --hard HEAD~1","git revert HEAD","git checkout HEAD~1","git reset --soft HEAD~1"],"correctIndex":1,"explanation":"git revert crée un nouveau commit qui inverse les changements d'un commit existant, sans modifier l'historique : sûr pour des commits déjà partagés. git reset réécrit l'historique.","difficulty":"medium"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Quelle commande remise temporairement de côté tes modifications non committées pour retrouver un working directory propre ?","code":"git stash","options":["git commit --amend","git stash","git reset --hard","git clean -fd"],"correctIndex":1,"explanation":"git stash sauvegarde les modifications en cours dans une pile temporaire et nettoie le working directory. On les récupère avec git stash pop. git reset --hard les détruirait.","difficulty":"easy"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Quelle affirmation décrit correctement la différence entre merge et rebase ?","code":null,"options":["merge réécrit l'historique, rebase crée un commit de fusion","merge crée un commit de fusion préservant l'historique, rebase réapplique les commits pour un historique linéaire","Les deux produisent exactement le même historique","rebase ne fonctionne qu'entre dépôts distants"],"correctIndex":1,"explanation":"git merge crée un commit de fusion conservant l'historique des deux branches. git rebase réapplique tes commits par-dessus la cible (historique linéaire, mais réécriture à éviter sur branches partagées).","difficulty":"medium"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Qu'est-ce qu'un merge fast-forward ?","code":null,"options":["Une fusion qui crée toujours un commit de merge","Une fusion où Git avance simplement le pointeur de branche car aucun commit divergent n'existe, sans créer de commit de merge","Une fusion qui annule les conflits automatiquement","Une fusion qui supprime la branche source"],"correctIndex":1,"explanation":"Un fast-forward se produit quand la branche cible n'a aucun commit nouveau depuis la divergence : Git avance simplement le pointeur jusqu'au dernier commit de la source, sans commit de fusion.","difficulty":"hard"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Que représente un état 'detached HEAD' dans Git ?","code":"git checkout <commit-hash>","options":["HEAD pointe directement sur un commit au lieu d'une branche","Le dépôt local a perdu sa connexion au remote","La branche courante a été supprimée","Un conflit de merge non résolu bloque HEAD"],"correctIndex":0,"explanation":"En 'detached HEAD', HEAD référence directement un commit précis et non l'extrémité d'une branche (après git checkout <hash>). Tout nouveau commit risque d'être perdu s'il n'est pas rattaché à une branche.","difficulty":"hard"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"À quoi sert la commande git cherry-pick <commit-hash> ?","code":"git cherry-pick <commit-hash>","options":["Fusionner entièrement une branche dans la branche courante","Appliquer un commit spécifique d'une autre branche sur la branche courante","Supprimer un commit de l'historique","Lister tous les commits d'une branche"],"correctIndex":1,"explanation":"git cherry-pick copie les changements d'un commit précis et les réapplique sur la branche courante. Utile pour récupérer un correctif isolé sans fusionner toute la branche.","difficulty":"medium"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Quel est le rôle du fichier .gitignore ?","code":null,"options":["Lister les fichiers à committer en priorité","Spécifier les fichiers et dossiers que Git doit ignorer (ne pas suivre)","Sauvegarder l'historique des commits supprimés","Définir les permissions d'accès au dépôt"],"correctIndex":1,"explanation":".gitignore liste des motifs de fichiers à ne pas suivre (binaires, node_modules, secrets...). Attention : il n'affecte pas les fichiers déjà suivis (utiliser git rm --cached).","difficulty":"easy"},
  {"category":"Git","subcategory":"Language knowledge","type":"mcq","question":"Dans un workflow de fork, que désignent habituellement 'origin' et 'upstream' ?","code":null,"options":["origin = ton fork, upstream = le dépôt original d'où tu as forké","origin = le dépôt original, upstream = ta branche locale","Les deux pointent toujours vers le même dépôt","origin = une branche, upstream = un tag"],"correctIndex":0,"explanation":"Par convention, 'origin' = ton propre fork (où tu pushes), 'upstream' = le dépôt original. On configure upstream pour récupérer les mises à jour du projet d'origine.","difficulty":"medium"}
];

const SQL_MCQ = [
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"Quelle clause filtre les lignes AVANT le regroupement, et laquelle filtre les groupes APRÈS agrégation ?","code":null,"options":["WHERE filtre avant le GROUP BY ; HAVING filtre après l'agrégation","HAVING filtre avant le GROUP BY ; WHERE filtre après","WHERE et HAVING sont strictement interchangeables","ORDER BY filtre les groupes après le GROUP BY"],"correctIndex":0,"explanation":"WHERE s'applique aux lignes avant le regroupement (sans fonction d'agrégat). HAVING s'applique aux groupes après GROUP BY et peut utiliser COUNT, SUM, etc.","difficulty":"junior"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"Customers a 10 lignes, Orders a 6 lignes (toutes liées à un client existant). Combien de lignes retourne au minimum cette requête ?","code":"SELECT c.id, o.id\nFROM Customers c\nLEFT JOIN Orders o ON o.customer_id = c.id;","options":["6 lignes","10 lignes (chaque client apparaît, NULL pour ceux sans commande)","16 lignes","60 lignes (produit cartésien)"],"correctIndex":1,"explanation":"Un LEFT JOIN renvoie TOUTES les lignes de gauche (Customers) plus les correspondances. Les clients sans commande apparaissent avec o.id = NULL. Donc au moins 10 lignes.","difficulty":"intermediaire"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"On veut compter le nombre d'employés par département, y compris les départements vides (0). Quelle expression est correcte ?","code":"SELECT d.name, ???\nFROM Departments d\nLEFT JOIN Employees e ON e.dept_id = d.id\nGROUP BY d.name;","options":["COUNT(*)","COUNT(e.id)","SUM(e.id)","COUNT(d.id)"],"correctIndex":1,"explanation":"COUNT(*) compterait la ligne générée par le LEFT JOIN pour un département sans employé (renvoie 1 au lieu de 0). COUNT(e.id) ignore les NULL et renvoie correctement 0.","difficulty":"intermediaire"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"Comment tester correctement qu'une colonne 'manager_id' n'a pas de valeur ?","code":null,"options":["WHERE manager_id = NULL","WHERE manager_id IS NULL","WHERE manager_id == NULL","WHERE manager_id <> 0"],"correctIndex":1,"explanation":"Toute comparaison avec = ou <> sur NULL renvoie UNKNOWN (jamais TRUE), donc `= NULL` ne ramène jamais de ligne. Il faut IS NULL (ou IS NOT NULL).","difficulty":"junior"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"Que garantit le D de l'acronyme ACID pour une transaction ?","code":null,"options":["Durabilité : une fois validée (COMMIT), la transaction survit même à une panne","Distribution : la transaction est répliquée sur plusieurs serveurs","Détermination : la transaction produit toujours le même résultat","Découplage : les transactions s'exécutent indépendamment du disque"],"correctIndex":0,"explanation":"ACID = Atomicité, Cohérence, Isolation, Durabilité. La Durabilité garantit qu'après un COMMIT, les modifications sont persistées définitivement, même en cas de crash.","difficulty":"intermediaire"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"Quelle affirmation décrit correctement une clé étrangère (FOREIGN KEY) ?","code":null,"options":["Elle garantit que chaque valeur de la colonne est unique","Elle référence la clé primaire d'une autre table et assure l'intégrité référentielle","Elle crée automatiquement un index clustered","Elle interdit les valeurs NULL dans toutes les colonnes"],"correctIndex":1,"explanation":"Une clé étrangère lie deux tables : ses valeurs doivent exister dans la clé primaire référencée. Elle empêche les lignes orphelines et bloque la suppression d'une ligne parente référencée.","difficulty":"junior"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"Quelle est la différence entre un index clustered et un index non-clustered (SQL Server) ?","code":null,"options":["Le clustered définit l'ordre physique des données (1 seul par table) ; le non-clustered est une structure séparée (plusieurs possibles)","Le non-clustered définit l'ordre physique ; le clustered est une structure séparée","Les deux trient physiquement les données et sont limités à un par table","Un index clustered ne peut exister que sur une colonne texte"],"correctIndex":0,"explanation":"L'index clustered détermine l'ordre de stockage physique (un seul par table). Un index non-clustered est une structure distincte avec clés triées et pointeurs ; on peut en créer plusieurs.","difficulty":"intermediaire"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"Que renvoie SELECT COUNT(grade) FROM Students si la table contient 5 lignes dont 2 ont grade = NULL ?","code":null,"options":["5","3","2","NULL"],"correctIndex":1,"explanation":"COUNT(colonne) compte uniquement les valeurs NON NULL. Avec 5 lignes dont 2 NULL, il reste 3. COUNT(*) aurait renvoyé 5.","difficulty":"junior"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"La 3e forme normale (3NF) ajoute quelle exigence par rapport à la 2NF ?","code":null,"options":["Chaque colonne doit contenir une valeur atomique","Aucune dépendance partielle sur une partie d'une clé composite","Aucune dépendance transitive : un attribut non-clé ne dépend que de la clé primaire","Chaque table doit posséder au moins un index"],"correctIndex":2,"explanation":"1NF = valeurs atomiques. 2NF = pas de dépendance partielle. 3NF = pas de dépendance transitive (un attribut non-clé ne doit pas dépendre d'un autre attribut non-clé).","difficulty":"intermediaire"},
  {"category":"SQL","subcategory":"Language knowledge","type":"mcq","question":"Comment limiter le résultat aux 3 premières lignes en SQL Server, puis en PostgreSQL ?","code":null,"options":["SQL Server : SELECT TOP 3 ... ; PostgreSQL : SELECT ... LIMIT 3","SQL Server : SELECT ... LIMIT 3 ; PostgreSQL : SELECT TOP 3 ...","Les deux utilisent ROWNUM <= 3","Les deux utilisent SELECT FIRST 3"],"correctIndex":0,"explanation":"SQL Server utilise SELECT TOP n (ou OFFSET/FETCH). PostgreSQL/MySQL/SQLite utilisent LIMIT n. La norme SQL standard est OFFSET ... FETCH FIRST n ROWS ONLY.","difficulty":"junior"}
];

const SQL_CODE = [
  {"category":"SQL","subcategory":"Problem solving","type":"code","language":"sql","prompt":"Table Employees(id, name, department, salary). Écris une requête qui retourne, pour chaque département, le salaire moyen, en ne gardant que les départements dont le salaire moyen dépasse 50000. Trie par salaire moyen décroissant.","setup":"CREATE TABLE Employees (id INTEGER, name TEXT, department TEXT, salary REAL); INSERT INTO Employees VALUES (1,'Alice','IT',60000),(2,'Bob','IT',70000),(3,'Carla','RH',40000),(4,'Dan','RH',42000),(5,'Eve','Vente',55000);","starterCode":"SELECT department, ...\nFROM Employees\n;","solution":"SELECT department, AVG(salary) AS avg_salary\nFROM Employees\nGROUP BY department\nHAVING AVG(salary) > 50000\nORDER BY avg_salary DESC;","tests":[{"input":"(IT,60000),(IT,70000),(RH,40000),(RH,42000),(Vente,55000)","expected":"IT -> 65000, Vente -> 55000 (RH exclu), trié décroissant"}],"explanation":"GROUP BY agrège par département ; HAVING filtre les GROUPES après agrégation (impossible avec WHERE sur un agrégat) ; ORDER BY ... DESC trie.","difficulty":"junior"},
  {"category":"SQL","subcategory":"Problem solving","type":"code","language":"sql","prompt":"Tables Customers(id, name) et Orders(id, customer_id, amount). Écris une requête listant TOUS les clients avec leur nombre de commandes, y compris ceux sans aucune commande (qui doivent afficher 0).","setup":"CREATE TABLE Customers (id INTEGER, name TEXT); CREATE TABLE Orders (id INTEGER, customer_id INTEGER, amount REAL); INSERT INTO Customers VALUES (1,'Alice'),(2,'Bob'); INSERT INTO Orders VALUES (10,1,100),(11,1,50);","starterCode":"SELECT c.name, ...\nFROM Customers c\n;","solution":"SELECT c.name, COUNT(o.id) AS nb_orders\nFROM Customers c\nLEFT JOIN Orders o ON o.customer_id = c.id\nGROUP BY c.id, c.name\nORDER BY nb_orders DESC;","tests":[{"input":"Customers (1,Alice),(2,Bob) ; Orders (10,1,100),(11,1,50)","expected":"Alice -> 2, Bob -> 0"}],"explanation":"Le LEFT JOIN conserve tous les clients. On compte COUNT(o.id) et non COUNT(*) : pour un client sans commande, o.id est NULL et n'est pas compté, donnant 0.","difficulty":"intermediaire"},
  {"category":"SQL","subcategory":"Problem solving","type":"code","language":"sql","prompt":"Table Employees(id, name, salary). Écris une requête qui retourne les employés dont le salaire est strictement supérieur au salaire moyen de l'ensemble. Utilise une sous-requête.","setup":"CREATE TABLE Employees (id INTEGER, name TEXT, salary REAL); INSERT INTO Employees VALUES (1,'A',30000),(2,'B',50000),(3,'C',70000);","starterCode":"SELECT name, salary\nFROM Employees\nWHERE ...\n;","solution":"SELECT name, salary\nFROM Employees\nWHERE salary > (SELECT AVG(salary) FROM Employees)\nORDER BY salary DESC;","tests":[{"input":"(A,30000),(B,50000),(C,70000) -> moyenne 50000","expected":"Seul C (70000) est retourné"}],"explanation":"La sous-requête scalaire calcule une valeur unique réutilisée dans le WHERE. Une fonction d'agrégat ne peut pas être placée directement dans WHERE, d'où la sous-requête.","difficulty":"intermediaire"},
  {"category":"SQL","subcategory":"Problem solving","type":"code","language":"sql","prompt":"Tables Products(id, name, category_id) et Categories(id, name). Écris une requête retournant le nom du produit et le nom de sa catégorie, uniquement pour les produits rattachés à une catégorie existante. Alias 'product_name' et 'category_name'.","setup":"CREATE TABLE Categories (id INTEGER, name TEXT); CREATE TABLE Products (id INTEGER, name TEXT, category_id INTEGER); INSERT INTO Categories VALUES (2,'Périphériques'); INSERT INTO Products VALUES (1,'Clavier',2),(2,'Souris',NULL);","starterCode":"SELECT ...\nFROM Products p\n;","solution":"SELECT p.name AS product_name, c.name AS category_name\nFROM Products p\nINNER JOIN Categories c ON c.id = p.category_id\nORDER BY c.name, p.name;","tests":[{"input":"Products (1,Clavier,2),(2,Souris,NULL) ; Categories (2,Périphériques)","expected":"Une ligne : Clavier / Périphériques (Souris exclue)"}],"explanation":"INNER JOIN ne conserve que les lignes avec correspondance des deux côtés ; un produit sans catégorie est exclu. Les alias clarifient le résultat.","difficulty":"junior"}
];

const AGILE_MCQ = [
  {"category":"Agile","subcategory":"Agile principles","type":"mcq","question":"Selon le Manifeste Agile, lequel de ces éléments est privilégié dans la première des 4 valeurs ?","code":null,"options":["Les processus et les outils plutôt que les individus et leurs interactions","Les individus et leurs interactions plutôt que les processus et les outils","La documentation exhaustive plutôt que le logiciel fonctionnel","Le suivi d'un plan plutôt que la collaboration"],"correctIndex":1,"explanation":"La première valeur du Manifeste Agile est « Les individus et leurs interactions PLUS QUE les processus et les outils ». Les éléments de droite ne sont pas rejetés, mais valorisés moins.","difficulty":"easy"},
  {"category":"Agile","subcategory":"Agile principles","type":"mcq","question":"Combien de principes sous-tendent le Manifeste Agile ?","code":null,"options":["4 principes","8 principes","12 principes","20 principes"],"correctIndex":2,"explanation":"Le Manifeste Agile s'appuie sur 4 valeurs et 12 principes (satisfaire le client par des livraisons rapides, accueillir le changement, livrer fréquemment...).","difficulty":"easy"},
  {"category":"Agile","subcategory":"Agile principles","type":"mcq","question":"Selon les principes Agile, quelle est la « mesure principale de l'avancement » d'un projet ?","code":null,"options":["Le nombre de lignes de code écrites","Le pourcentage de documentation rédigée","Le logiciel fonctionnel (qui marche)","Le nombre d'heures travaillées par l'équipe"],"correctIndex":2,"explanation":"Le 7e principe Agile : « Un logiciel opérationnel est la principale mesure d'avancement ». On mesure la valeur livrée, pas l'effort fourni.","difficulty":"medium"},
  {"category":"Agile","subcategory":"Agile principles","type":"mcq","question":"Dans une équipe Kanban, que limite-t-on principalement pour fluidifier le travail ?","code":null,"options":["La durée des itérations (timeboxing strict)","Le nombre de tâches en cours simultanément (WIP / Work In Progress)","Le nombre de membres de l'équipe","Le nombre de réunions par semaine"],"correctIndex":1,"explanation":"Kanban repose sur la limitation du WIP : on plafonne le nombre de tâches « en cours » pour réduire le multitâche et accélérer le flux. Contrairement à Scrum, pas d'itérations à durée fixe.","difficulty":"medium"},
  {"category":"Agile","subcategory":"Agile principles","type":"mcq","question":"Quelle différence majeure distingue Scrum de Kanban ?","code":null,"options":["Kanban utilise des sprints à durée fixe, pas Scrum","Scrum fonctionne par sprints à durée fixe (timeboxés) et rôles définis, Kanban est un flux continu sans itérations imposées","Scrum interdit tout tableau visuel, Kanban l'impose","Il n'existe aucune différence, ce sont des synonymes"],"correctIndex":1,"explanation":"Scrum est cadencé par des sprints timeboxés, avec des rôles et événements précis. Kanban est un flux continu, sans itérations ni rôles imposés, centré sur la visualisation et la limite du WIP.","difficulty":"medium"},
  {"category":"Agile","subcategory":"Agile principles","type":"mcq","question":"Qu'est-ce qu'une « user story » bien formulée ?","code":null,"options":["Une spécification technique détaillée écrite par les développeurs","Une description courte d'un besoin du point de vue de l'utilisateur, souvent au format « En tant que… je veux… afin de… »","La liste exhaustive des bugs à corriger","Le compte rendu de la Daily Scrum"],"correctIndex":1,"explanation":"Une user story décrit un besoin du point de vue de l'utilisateur : « En tant que [rôle], je veux [action] afin de [bénéfice] ». Concise, elle déclenche une conversation plutôt qu'une spécification figée.","difficulty":"easy"},
  {"category":"Agile","subcategory":"Agile principles","type":"mcq","question":"À quoi servent les « story points » lors de l'estimation ?","code":null,"options":["À mesurer le nombre exact d'heures de travail nécessaires","À estimer l'effort/la complexité relative d'une user story, pas une durée précise","À noter la qualité du code livré","À compter le nombre de membres affectés à une tâche"],"correctIndex":1,"explanation":"Les story points estiment l'effort RELATIF (complexité, incertitude, volume), pas des heures. On utilise souvent Fibonacci (1, 2, 3, 5, 8...) pour refléter l'incertitude croissante.","difficulty":"medium"},
  {"category":"Agile","subcategory":"Agile principles","type":"mcq","question":"Que représente la « vélocité » (velocity) d'une équipe Scrum ?","code":null,"options":["La vitesse de frappe au clavier des développeurs","Le nombre moyen de story points complétés par sprint","Le temps de réponse de l'application en production","Le délai entre deux Daily Scrum"],"correctIndex":1,"explanation":"La vélocité est le nombre de story points qu'une équipe termine en moyenne par sprint. Elle sert à prévoir la capacité future ; c'est un indicateur interne, pas un outil de comparaison entre équipes.","difficulty":"medium"},
  {"category":"Agile","subcategory":"Scrum events","type":"mcq","question":"Quel est l'objectif principal de la Daily Scrum (mêlée quotidienne) ?","code":null,"options":["Faire un compte rendu détaillé au manager","Permettre aux développeurs de synchroniser leur travail et planifier les prochaines 24h vers l'objectif du sprint","Estimer toutes les user stories du backlog","Faire la démonstration du produit aux parties prenantes"],"correctIndex":1,"explanation":"La Daily Scrum (15 min max) sert aux développeurs à inspecter l'avancement vers le Sprint Goal et adapter le plan des prochaines 24h. C'est une réunion de l'équipe de dev, pas un reporting.","difficulty":"easy"},
  {"category":"Agile","subcategory":"Scrum events","type":"mcq","question":"Quel événement Scrum a pour but d'inspecter la collaboration de l'équipe et de l'améliorer ?","code":null,"options":["La Sprint Review","La Sprint Planning","La Sprint Retrospective (rétrospective)","La Daily Scrum"],"correctIndex":2,"explanation":"La Rétrospective clôt le sprint : l'équipe inspecte son fonctionnement (process, outils, collaboration) et identifie des améliorations. La Sprint Review, elle, porte sur le PRODUIT (l'Increment).","difficulty":"medium"},
  {"category":"Agile","subcategory":"Scrum events","type":"mcq","question":"Qui est responsable de la gestion et de la priorisation du Product Backlog ?","code":null,"options":["Le Scrum Master","Le Product Owner","L'équipe de développement","Le directeur technique (CTO)"],"correctIndex":1,"explanation":"Le Product Owner maximise la valeur du produit et gère le Product Backlog : il en ordonne (priorise) les éléments. Le Scrum Master facilite le process, les développeurs réalisent l'Increment.","difficulty":"easy"},
  {"category":"Agile","subcategory":"Scrum events","type":"mcq","question":"Qu'est-ce que la « Definition of Done » (Définition de Terminé) en Scrum ?","code":null,"options":["La date de fin prévue du projet","Un ensemble partagé de critères de qualité qu'un incrément doit remplir pour être considéré comme terminé","La liste des tâches restant à faire dans le sprint","Le moment où le Product Owner valide oralement une story"],"correctIndex":1,"explanation":"La Definition of Done est un ensemble formel et partagé de critères (tests passés, code revu, déployable...) garantissant qu'un incrément est réellement terminé et potentiellement livrable.","difficulty":"medium"}
];

const QUESTIONS = [].concat(
  CSHARP_MCQ, CSHARP_CODE,
  ASPNET_MCQ,
  EF_MCQ,
  ANGULAR_MCQ,
  JS_MCQ, JS_CODE,
  CSS_MCQ,
  GIT_MCQ,
  SQL_MCQ, SQL_CODE,
  AGILE_MCQ
);

// Conseils affichés avant le test (issus des vraies plateformes)
const TIPS = [
  "Lis chaque énoncé attentivement et réponds uniquement à ce qui est demandé.",
  "Gère ton temps : ne bloque pas sur une question, le chronomètre est global.",
  "Pour le code, pense aux cas limites : valeurs nulles, listes vides, grands volumes.",
  "Sécurise d'abord les questions faciles : chaque point compte.",
  "En cas de doute, élimine les réponses manifestement fausses."
];
